# Generated by Django 3.2.7 on 2021-10-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='technologie',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
