# Generated by Django 3.2.7 on 2022-03-21 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0002_projet_technologie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='fait',
            options={'verbose_name_plural': 'Faits'},
        ),
        migrations.AlterModelOptions(
            name='imageprojet',
            options={'verbose_name_plural': 'Image De Projets'},
        ),
        migrations.AlterModelOptions(
            name='projet',
            options={'verbose_name_plural': 'Projets'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='temoignage',
            options={'verbose_name_plural': 'Témoignages'},
        ),
    ]
