# Generated by Django 3.2.7 on 2021-09-27 12:10

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoriepapier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("date_add", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Categoriepapier",
                "verbose_name_plural": "Categoriepapiers",
            },
        ),
        migrations.CreateModel(
            name="Competence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("pourcentage", models.IntegerField(default=0)),
                ("date_add", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Competence",
                "verbose_name_plural": "Competences",
            },
        ),
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descriptionAPropos", models.TextField()),
                ("descriptionFait", models.TextField()),
                ("descriptionCompetence", models.TextField()),
                ("descriptionResume", models.TextField()),
                ("descriptionDiplome", models.TextField(blank=True, null=True)),
                ("descriptionPortfolio", models.TextField()),
                ("descriptionService", models.TextField()),
                ("descriptionTemoignage", models.TextField()),
                ("descriptionContact", models.TextField()),
                ("date_add", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Configuration",
                "verbose_name_plural": "Configurations",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("sujet", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("date_add", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
            },
        ),
        migrations.CreateModel(
            name="Optionapropos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("information", models.CharField(max_length=255)),
                ("date_add", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Optionapropos",
                "verbose_name_plural": "Optionaproposs",
            },
        ),
        migrations.CreateModel(
            name="Optionresume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("date", models.CharField(max_length=255)),
                ("description", tinymce.models.HTMLField()),
                ("date_add", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Optionresume",
                "verbose_name_plural": "Optionresumes",
            },
        ),
        migrations.CreateModel(
            name="Siteweb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("prenom", models.CharField(max_length=255)),
                ("photoProfil", models.FileField(upload_to="Siteweb_file")),
                ("photoCouverture", models.FileField(upload_to="Siteweb_file")),
                ("telephone", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("adresse", models.CharField(max_length=255)),
                ("localisation", models.TextField()),
                ("date_add", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Siteweb",
                "verbose_name_plural": "Sitewebs",
            },
        ),
        migrations.CreateModel(
            name="Sociaux",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("icone", models.CharField(max_length=255)),
                ("lien", models.CharField(max_length=255)),
                ("date_add", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Social",
                "verbose_name_plural": "Sociaux",
            },
        ),
        migrations.CreateModel(
            name="Travail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("liste", models.CharField(max_length=255)),
                ("date_add", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Travail",
                "verbose_name_plural": "Travails",
            },
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("date_add", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                (
                    "option",
                    models.ManyToManyField(
                        related_name="optionResume", to="siteweb.Optionresume"
                    ),
                ),
            ],
            options={
                "verbose_name": "Resume",
                "verbose_name_plural": "Resumes",
            },
        ),
        migrations.CreateModel(
            name="Diplome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("image", models.FileField(upload_to="Diplome_file")),
                ("date_add", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                (
                    "categorie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorie_papier",
                        to="siteweb.categoriepapier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diplome",
                "verbose_name_plural": "Diplomes",
            },
        ),
        migrations.CreateModel(
            name="Apropos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("date_add", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                (
                    "option",
                    models.ManyToManyField(
                        related_name="detailApropos", to="siteweb.Optionapropos"
                    ),
                ),
            ],
            options={
                "verbose_name": "Apropos",
                "verbose_name_plural": "Aproposs",
            },
        ),
    ]
