# Generated by Django 3.2.7 on 2021-09-27 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("siteweb", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reseauxsocial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lien", models.CharField(max_length=255)),
                ("date_add", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Reseauxsocial",
                "verbose_name_plural": "Reseauxsocials",
            },
        ),
        migrations.CreateModel(
            name="Socialicone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("icone", models.CharField(max_length=255)),
                ("date_add", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Socialicone",
                "verbose_name_plural": "Socialicones",
            },
        ),
        migrations.DeleteModel(
            name="Sociaux",
        ),
        migrations.AddField(
            model_name="reseauxsocial",
            name="sociaux",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_icon",
                to="siteweb.socialicone",
            ),
        ),
    ]
