# Generated by Django 3.2 on 2021-09-28 17:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0003_optionresume_nomstructure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionresume',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
