# Generated by Django 3.2.7 on 2021-09-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteweb", "0004_alter_optionresume_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("image", models.FileField(upload_to="Certificat_file")),
                ("date_add", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Certificat",
                "verbose_name_plural": "Certificats",
            },
        ),
        migrations.RemoveField(
            model_name="diplome",
            name="categorie",
        ),
        migrations.DeleteModel(
            name="Categoriepapier",
        ),
        migrations.DeleteModel(
            name="Diplome",
        ),
    ]
