# Generated by Django 3.2.7 on 2022-03-21 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0005_auto_20210929_1924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apropos',
            options={'verbose_name_plural': 'A Propos'},
        ),
        migrations.AlterModelOptions(
            name='certificat',
            options={'verbose_name_plural': 'Certificats'},
        ),
        migrations.AlterModelOptions(
            name='competence',
            options={'verbose_name_plural': 'Compétences'},
        ),
        migrations.AlterModelOptions(
            name='configuration',
            options={'verbose_name_plural': 'Configurations'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='optionapropos',
            options={'verbose_name_plural': 'Options A Propos'},
        ),
        migrations.AlterModelOptions(
            name='optionresume',
            options={'ordering': ['-date_add'], 'verbose_name_plural': 'Options Résumes'},
        ),
        migrations.AlterModelOptions(
            name='reseauxsocial',
            options={'verbose_name_plural': 'Réseaux Sociaux'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name_plural': 'Résumes'},
        ),
        migrations.AlterModelOptions(
            name='siteweb',
            options={'verbose_name_plural': 'Site Webs'},
        ),
        migrations.AlterModelOptions(
            name='socialicone',
            options={'verbose_name_plural': 'Icones Réseaux Sociaux'},
        ),
        migrations.AlterModelOptions(
            name='travail',
            options={'verbose_name_plural': 'Travails'},
        ),
        migrations.RenameField(
            model_name='optionresume',
            old_name='date',
            new_name='periode',
        ),
    ]
